name: bloodbridgeflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.0.0

  # Image and Location
  image_picker: ^1.0.7
  geolocator: ^10.1.1

  # HTTP requests for notifications
  http: ^1.1.0

  # Animations
  lottie: ^3.1.0

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/splash.json
    - assets/icons/logo.png

#################################################################
# App Icon Generation
#################################################################
flutter_launcher_icons:
  image_path: "assets/icons/logo.png"

  android: true
  ios: true

  web:
    generate: true
    image_path: "assets/icons/logo.png"

  windows:
    generate: true
    image_path: "assets/icons/logo.png"

  macos:
    generate: true
    image_path: "assets/icons/logo.png"